sudo: true
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: gae
  project: pro-bruin-207112
  keyfile: gae.json
  verbosity: debug
  default: true
  on: master
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_fb95c9318e23_key -iv $encrypted_fb95c9318e23_iv
  -in gae.json.enc -out gae.json -d
before_deploy: "./create_env_file.sh"
